[profile.default]
src      = "contracts"
out      = "out"
test     = "test"
libs     = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/"]

[profile.default.fuzz]
runs = 256

[rpc_endpoints]
monad_testnet = "${MONAD_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC}"

[etherscan]
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
